"""latest

Revision ID: 8cf5269df348
Revises: b6c2545a61ef
Create Date: 2025-11-03 16:31:34.751954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf5269df348'
down_revision = 'b6c2545a61ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
