from io import BytesIO

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


def render_invoice_pdf(invoice: dict, client: dict, items: list[dict]) -> bytes:
    """
    Very simple PDF to keep the stack light (ReportLab). You can swap this out
    for a headless HTML→PDF adapter later without changing API contracts.
    """
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, height - 50, f"Invoice {invoice['number']}")

    c.setFont("Helvetica", 10)
    c.drawString(
        50, height - 70, f"Issue date: {invoice['issue_date']}  Due: {invoice['due_date']}"
    )
    c.drawString(50, height - 85, f"Client: {client['name']}  Email: {client.get('email', '')}")

    y = height - 120
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Description")
    c.drawString(350, y, "Qty")
    c.drawString(400, y, "Unit (R cents)")
    c.drawString(520, y, "Line Total")
    y -= 20
    c.setFont("Helvetica", 10)

    for it in items:
        c.drawString(50, y, it["description"][:60])
        c.drawRightString(380, y, f"{it['qty']}")
        c.drawRightString(480, y, f"{it['unit_price_cents']}")
        c.drawRightString(560, y, f"{it['line_total_cents']}")
        y -= 16
        if y < 100:
            c.showPage()
            y = height - 100

    y -= 10
    c.setFont("Helvetica-Bold", 12)
    c.drawRightString(560, y, f"Subtotal: {invoice['subtotal_cents']}")
    y -= 16
    c.drawRightString(560, y, f"Tax: {invoice['tax_cents']}")
    y -= 16
    c.drawRightString(560, y, f"Total: {invoice['total_cents']}")
    y -= 16
    c.drawRightString(560, y, f"Balance: {invoice['balance_cents']}")
    y -= 24

    c.setFont("Helvetica-Oblique", 9)
    c.drawString(50, 60, "Generated by Invoice Tracker")
    c.showPage()
    c.save()
    return buffer.getvalue()
